//
//  WorkSpace.swift
//  Manifests
//
//  Created by DDD on 6/7/24.
//

import Foundation
import ProjectDescription
import ProjectTemplatePlugin

let workspace = Workspace(
  name: Project.Environment.appName,
  projects: [
    "Projects/**"
  ],
  // 커버리지 대상을 자사 모듈로 한정한다.
  // 지정하지 않으면 외부 SPM 패키지까지 profdata 에 들어가 xccov 리포트가 수십 분씩 걸린다.
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .enabled(
      codeCoverageMode: .targets([
        .project(path: "Projects/App", target: "DDDAttendance"),

        .project(path: "Projects/Core/DDDCoreLogger", target: "DDDCoreLogger"),
        .project(path: "Projects/Core/DDDCoreUI", target: "DDDCoreUI"),
        .project(path: "Projects/Core/DDDCoreUtility", target: "DDDCoreUtility"),
        .project(path: "Projects/Core/DDDThirdParty", target: "DDDThirdParty"),

        .project(path: "Projects/UI/DDDDesignKit", target: "DDDDesignKit"),
        .project(path: "Projects/UI/DDDSharedUI", target: "DDDSharedUI"),

        .project(path: "Projects/Network/Foundations", target: "Foundations"),
        .project(path: "Projects/Network/Networks", target: "Networks"),
        .project(path: "Projects/Network/ThirdPartys", target: "ThirdPartys"),

        .project(path: "Projects/Data/API", target: "API"),
        .project(path: "Projects/Data/Model", target: "Model"),
        .project(path: "Projects/Data/Repository", target: "Repository"),
        .project(path: "Projects/Data/Service", target: "Service"),

        .project(path: "Projects/Domain/DomainInterface", target: "DomainInterface"),
        .project(path: "Projects/Domain/Entity", target: "Entity"),
        .project(path: "Projects/Domain/UseCase", target: "UseCase"),

        .project(path: "Projects/Feature/Auth", target: "Auth"),
        .project(path: "Projects/Feature/Management", target: "Management"),
        .project(path: "Projects/Feature/Member", target: "Member"),
        .project(path: "Projects/Feature/OnBoarding", target: "OnBoarding"),
        .project(path: "Projects/Feature/FeatureAssembly", target: "FeatureAssembly"),
        .project(path: "Projects/Feature/Profile", target: "Profile"),
        .project(path: "Projects/Feature/Splash", target: "Splash"),
        .project(path: "Projects/Feature/Web", target: "Web")
      ])
    )
  )
)
